<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $report->title }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .title {
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 10px;
        }
        .description {
            color: #666;
            margin-bottom: 5px;
        }
        .meta {
            font-size: 12px;
            color: #888;
        }
        .section {
            margin-bottom: 30px;
        }
        .section-title {
            font-size: 18px;
            font-weight: bold;
            margin-bottom: 15px;
            border-bottom: 1px solid #eee;
            padding-bottom: 5px;
        }
        .grid {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 20px;
        }
        .item {
            margin-bottom: 10px;
        }
        .label {
            font-weight: bold;
            color: #666;
        }
        .value {
            color: #333;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            padding: 8px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        th {
            background-color: #f8f9fa;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">{{ $report->title }}</div>
        <div class="description">{{ $report->description }}</div>
        <div class="meta">
            Generated by {{ $report->user->name ?? 'Unknown User' }} on {{ $report->generated_at->format('F j, Y g:i A') }}
        </div>
    </div>

    <div class="content">
        @switch($report->type)
            @case('occupancy')
                <div class="section">
                    <div class="section-title">Occupancy Overview</div>
                    <div class="grid">
                        <div class="item">
                            <span class="label">Total Units:</span>
                            <span class="value">{{ $report->data['total_units'] }}</span>
                        </div>
                        <div class="item">
                            <span class="label">Occupied Units:</span>
                            <span class="value">{{ $report->data['occupied_units'] }}</span>
                        </div>
                        <div class="item">
                            <span class="label">Vacant Units:</span>
                            <span class="value">{{ $report->data['vacant_units'] }}</span>
                        </div>
                        <div class="item">
                            <span class="label">Occupancy Rate:</span>
                            <span class="value">{{ $report->data['occupancy_rate'] }}%</span>
                        </div>
                    </div>
                </div>
                @break

            @case('revenue')
                <div class="section">
                    <div class="section-title">Revenue Overview</div>
                    <div class="grid">
                        <div class="item">
                            <span class="label">Total Revenue:</span>
                            <span class="value">${{ number_format($report->data['total_revenue'], 2) }}</span>
                        </div>
                        <div class="item">
                            <span class="label">Total Transactions:</span>
                            <span class="value">{{ $report->data['total_transactions'] }}</span>
                        </div>
                        <div class="item">
                            <span class="label">Average Payment:</span>
                            <span class="value">${{ number_format($report->data['average_payment'], 2) }}</span>
                        </div>
                    </div>
                </div>

                <div class="section">
                    <div class="section-title">Monthly Revenue</div>
                    <table>
                        <thead>
                            <tr>
                                <th>Month</th>
                                <th>Total</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($report->data['monthly_revenue'] as $month)
                                <tr>
                                    <td>{{ \Carbon\Carbon::createFromFormat('Y-m', $month['month'])->format('F Y') }}</td>
                                    <td>${{ number_format($month['total'], 2) }}</td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
                @break

            @case('maintenance')
                <div class="section">
                    <div class="section-title">Maintenance Overview</div>
                    <div class="grid">
                        <div class="item">
                            <span class="label">Total Requests:</span>
                            <span class="value">{{ $report->data['total_requests'] }}</span>
                        </div>
                        <div class="item">
                            <span class="label">Average Resolution Time:</span>
                            <span class="value">{{ round($report->data['average_resolution_time'], 1) }} hours</span>
                        </div>
                    </div>
                </div>

                <div class="section">
                    <div class="section-title">Status Breakdown</div>
                    <table>
                        <thead>
                            <tr>
                                <th>Status</th>
                                <th>Count</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($report->data['status_breakdown'] as $status)
                                <tr>
                                    <td>{{ ucfirst($status['status']) }}</td>
                                    <td>{{ $status['count'] }}</td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
                @break
        @endswitch
    </div>
</body>
</html> 