@extends('layouts.app')

@section('title', $report->title)

@section('content')
<div class="py-12">
    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
        <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
            <div class="p-6">
                <div class="flex justify-between items-center mb-6">
                    <h2 class="text-2xl font-bold text-gray-900">{{ $report->title }}</h2>
                    <div class="flex space-x-4">
                        <a href="{{ route('reports.download', $report) }}" class="inline-flex items-center px-4 py-2 bg-gray-800 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-gray-700">
                            Download PDF
                        </a>
                    </div>
                </div>

                <div class="mb-6">
                    <p class="text-gray-600">{{ $report->description }}</p>
                    <p class="text-sm text-gray-500 mt-2">
                        Generated by {{ $report->user->name ?? 'Unknown User' }} on {{ $report->generated_at->format('F j, Y g:i A') }}
                    </p>
                </div>

                <div class="mt-8">
                    @switch($report->type)
                        @case('occupancy')
                            <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                                <div>
                                    <h3 class="text-lg font-medium text-gray-900 mb-4">Occupancy Overview</h3>
                                    <div class="bg-white shadow rounded-lg p-6">
                                        <div class="space-y-4">
                                            <div class="flex items-center justify-between">
                                                <span class="text-sm font-medium text-gray-500">Total Units</span>
                                                <span class="text-sm font-medium text-gray-900">{{ $report->data['total_units'] }}</span>
                                            </div>
                                            <div class="flex items-center justify-between">
                                                <span class="text-sm font-medium text-gray-500">Occupied Units</span>
                                                <span class="text-sm font-medium text-gray-900">{{ $report->data['occupied_units'] }}</span>
                                            </div>
                                            <div class="flex items-center justify-between">
                                                <span class="text-sm font-medium text-gray-500">Vacant Units</span>
                                                <span class="text-sm font-medium text-gray-900">{{ $report->data['vacant_units'] }}</span>
                                            </div>
                                            <div class="flex items-center justify-between">
                                                <span class="text-sm font-medium text-gray-500">Occupancy Rate</span>
                                                <span class="text-sm font-medium text-gray-900">{{ $report->data['occupancy_rate'] }}%</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            @break

                        @case('revenue')
                            <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                                <div>
                                    <h3 class="text-lg font-medium text-gray-900 mb-4">Revenue Overview</h3>
                                    <div class="bg-white shadow rounded-lg p-6">
                                        <div class="space-y-4">
                                            <div class="flex items-center justify-between">
                                                <span class="text-sm font-medium text-gray-500">Total Revenue</span>
                                                <span class="text-sm font-medium text-gray-900">${{ number_format($report->data['total_revenue'], 2) }}</span>
                                            </div>
                                            <div class="flex items-center justify-between">
                                                <span class="text-sm font-medium text-gray-500">Total Transactions</span>
                                                <span class="text-sm font-medium text-gray-900">{{ $report->data['total_transactions'] }}</span>
                                            </div>
                                            <div class="flex items-center justify-between">
                                                <span class="text-sm font-medium text-gray-500">Average Payment</span>
                                                <span class="text-sm font-medium text-gray-900">${{ number_format($report->data['average_payment'], 2) }}</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div>
                                    <h3 class="text-lg font-medium text-gray-900 mb-4">Monthly Revenue</h3>
                                    <div class="bg-white shadow rounded-lg p-6">
                                        <div class="space-y-4">
                                            @foreach($report->data['monthly_revenue'] as $month)
                                                <div class="flex items-center justify-between">
                                                    <span class="text-sm font-medium text-gray-500">{{ \Carbon\Carbon::createFromFormat('Y-m', $month['month'])->format('F Y') }}</span>
                                                    <span class="text-sm font-medium text-gray-900">${{ number_format($month['total'], 2) }}</span>
                                                </div>
                                            @endforeach
                                        </div>
                                    </div>
                                </div>
                            </div>
                            @break

                        @case('maintenance')
                            <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                                <div>
                                    <h3 class="text-lg font-medium text-gray-900 mb-4">Maintenance Overview</h3>
                                    <div class="bg-white shadow rounded-lg p-6">
                                        <div class="space-y-4">
                                            <div class="flex items-center justify-between">
                                                <span class="text-sm font-medium text-gray-500">Total Requests</span>
                                                <span class="text-sm font-medium text-gray-900">{{ $report->data['total_requests'] }}</span>
                                            </div>
                                            <div class="flex items-center justify-between">
                                                <span class="text-sm font-medium text-gray-500">Average Resolution Time</span>
                                                <span class="text-sm font-medium text-gray-900">{{ round($report->data['average_resolution_time'], 1) }} hours</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div>
                                    <h3 class="text-lg font-medium text-gray-900 mb-4">Status Breakdown</h3>
                                    <div class="bg-white shadow rounded-lg p-6">
                                        <div class="space-y-4">
                                            @foreach($report->data['status_breakdown'] as $status)
                                                <div class="flex items-center justify-between">
                                                    <span class="text-sm font-medium text-gray-500">{{ ucfirst($status['status']) }}</span>
                                                    <span class="text-sm font-medium text-gray-900">{{ $status['count'] }}</span>
                                                </div>
                                            @endforeach
                                        </div>
                                    </div>
                                </div>
                            </div>
                            @break
                    @endswitch
                </div>
            </div>
        </div>
    </div>
</div>
@endsection 